CREATE FUNCTION DBO.UF_GETTOTALPRICE(@PRICE MONEY, 
@DISCOUNT DECIMAL(18, 2), @QUANTITY INT) RETURNS MONEY 
AS 
	BEGIN DECLARE @Result MONEY
	SET
	    @Result = (@Price * @Quantity) * (100 - @Discount) / 100
	RETURN @Result
	END
