CREATE TABLE [dbo].[Products] (
	[Id] INT IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL,
	[Price] MONEY NOT NULL,
	[Discount] DECIMAL(18, 2) NOT NULL DEFAULT 0,
	[Stock] DECIMAL(18, 2) NOT NULL
);
GO

-- ADD DEFAULT TO EXISTING COLUMN
ALTER TABLE [dbo].[Products]
ADD DEFAULT 0 FOR [Stock];
GO

-- ADD CHECK CONSTRAINT TO EXISTING COLUMN
ALTER TABLE [dbo].[Products]
ADD CONSTRAINT CK_Products_Price CHECK ([Price] > 0);
GO